### ISSUE TITLE
Лишняя строчка

### ISSUE THREAD

**Issue by SashaTalk** [maxim-adaev-production/notes-on-batch#3]
![image](https://user-images.githubusercontent.com/76222964/148786912-0d4f1a3c-7a17-49cd-bcf6-546ca5f14593.png)

**Comment by m-a-prod** [comment]
Это оставлено место под заметки, первый отступ для красоты, на втором будут заметки. Про пробел, я не хочу чтобы там был пробел.

**Comment by SashaTalk** [comment]
STUIS требует пробела. Так красивее

**Comment by m-a-prod** [comment]
ок
