### ISSUE TITLE
Тут set /p а не choice

### ISSUE THREAD

**Issue by SashaTalk** [maxim-adaev-production/notes-on-batch#6]
![image](https://user-images.githubusercontent.com/76222964/148790394-621428e9-37fa-4035-975b-b21404051fa8.png)

**Comment by m-a-prod** [comment]
Там set /p, почитай код внимательнее.

**Comment by SashaTalk** [comment]
> Там set /p, почитай код внимательнее.

ты долбаёб, я написал что тут `set /p` а должен быть `choice`

**Comment by m-a-prod** [comment]
Скажи мне пожалуйста, зачем тут choice, как я буду заметки выбирать, тут интерфейс построен как в Say Online.

**Comment by SashaTalk** [comment]
> Скажи мне пожалуйста, зачем тут choice, как я буду заметки выбирать, тут интерфейс построен как в Say Online.

Тогда сделай всё в `set /p`.
Да и `choice` пищит не приятно

**Comment by m-a-prod** [comment]
Сделал уже

**Comment by SashaTalk** [comment]
> Сделал уже

молодец
